# Generated by Django 5.0.4 on 2024-04-14 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoidComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='WasteComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=32)),
            ],
        ),
        migrations.RenameModel(
            old_name='Lab',
            new_name='Branch',
        ),
        migrations.RemoveField(
            model_name='product',
            name='barcode',
        ),
        migrations.RemoveField(
            model_name='product',
            name='variant',
        ),
        migrations.RenameField(
            model_name='brand',
            old_name='labs',
            new_name='branches',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='pickup_time',
            new_name='picked_up_at_time',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='cooked_at',
            new_name='started_prep_at',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='lab',
            new_name='branch',
        ),
        migrations.RemoveField(
            model_name='order',
            name='started_at',
        ),
        migrations.AddField(
            model_name='order',
            name='finished_prep_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('received', 'Received'), ('processing', 'Processing'), ('r for packing', 'Ready for packing'), ('r for pickup', 'Ready for pickup'), ('delivered', 'Delivered'), ('waste', 'Waste'), ('void', 'Void')], default='received', max_length=15),
        ),
        migrations.AlterField(
            model_name='review',
            name='value',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0, verbose_name='Rating value'),
        ),
        migrations.AlterField(
            model_name='order',
            name='void_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.voidcomment'),
        ),
        migrations.AddField(
            model_name='order',
            name='waste_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.wastecomment'),
        ),
        migrations.DeleteModel(
            name='Barcode',
        ),
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.DeleteModel(
            name='Variant',
        ),
    ]
