# Generated by Django 5.0.4 on 2024-04-14 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_category_alter_address_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_fees',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='refund_delivery_charge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
